name: Build .NET Framework 4.5.2 application

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework 4.5.2
      run: |
        Invoke-WebRequest "https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net452-developer-pack-offline-installer" -OutFile "dotNetFx45_Full_setup.exe"
        ./dotNetFx45_Full_setup.exe /q /norestart

    - name: Build solution
      run: |
        cd ProjectThree
        msbuild ProjectThree.sln /p:Configuration=Release

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ProjectThree-build
        path: ProjectThree\bin\Release
