name: Build .NET Framework 4.5.2 application

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework 4.5.2
      run: |
        Invoke-WebRequest "https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe" -OutFile "NDP452-KB2901907-x86-x64-AllOS-ENU.exe"
        ./NDP452-KB2901907-x86-x64-AllOS-ENU.exe /q /norestart

    - name: Build solution
      run: |
        cd ProjectThree
        msbuild ProjectThree.sln /p:Configuration=Release

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ProjectThree-build
        path: ProjectThree\bin\Release

