name: Build .NET Framework 4.5.2 application

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework 4.5.2
      run: |
        Invoke-WebRequest "https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx45_Full_setup.exe" -OutFile "dotNetFx45_Full_setup.exe"
        ./dotNetFx45_Full_setup.exe /q /norestart

    - name: Build solution
      run: |
        cd ProjectThree
        msbuild ProjectThree.sln /p:Configuration=Release

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ProjectThree-build
        path: ProjectThree\bin\Release
