name: Build .NET Framework 4.5.2 application

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build solution
      run: |
        cd ProjectThree
        msbuild ProjectThree.sln /p:Configuration=Release

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ProjectThree-build
        path: ProjectThree\bin\Release
