name: Build .NET Framework 4.5.2 Application

on: [push]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework 4.5.2
      run: |
        Write-Host "Installing .NET Framework 4.5.2"
        Add-WindowsFeature -Name Net-Framework-45-Features,Net-Framework-Core
        Write-Host ".NET Framework 4.5.2 Installed"

    - name: Restore dependencies
      run: |
        Write-Host "Restoring dependencies"
        & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\msbuild.exe' /t:restore

    - name: Build solution
      run: |
        Write-Host "Building solution"
        & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\msbuild.exe' /t:build
